data:
  gpu: 0
  num_workers: 8
  train_dataset: /tmp/cifar_train.beton
  val_dataset: /tmp/cifar_test.beton

training:
  batch_size: 4196
  lr: 7.716366708524112
  epochs: 225
  momentum: 0.02386004434170004
  weight_decay: 0.009571506019582308
  label_smoothing: 0.38809647522572255
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 146

