data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 7.876773592033604
  epochs: 165
  momentum: 0.833702936395007
  weight_decay: 0.0004206892470009781
  label_smoothing: 0.3267775109774098
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 29

seed:
  seednum: 21208

