data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.6789415068988224
  epochs: 239
  momentum: 0.9858550078368048
  weight_decay: 8.937187150251162e-05
  label_smoothing: 0.17153937999663169
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 121

seed:
  seednum: 16010

