data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.5010809006820227
  epochs: 107
  momentum: 0.1794512032620041
  weight_decay: 0.010540307902212427
  label_smoothing: 0.4971753037864076
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 60

seed:
  seednum: 26185

