data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.048880745200214834
  epochs: 77
  momentum: 0.3358283310467497
  weight_decay: 0.0020118836675124
  label_smoothing: 0.3126016433863022
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 32

seed:
  seednum: 9277

