data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.28422013905868
  epochs: 222
  momentum: 0.1805633746697528
  weight_decay: 6.252578666246006e-06
  label_smoothing: 0.07621477211959855
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 80

seed:
  seednum: 24315

