data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.5538556907762427
  epochs: 288
  momentum: 0.8344492676940377
  weight_decay: 0.02055799937063668
  label_smoothing: 0.2921960587763984
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 219

seed:
  seednum: 2452

