data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.9405189022461881
  epochs: 300
  momentum: 0.9998391799423363
  weight_decay: 3.606703327906519e-05
  label_smoothing: 0.11902901777705663
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 296

seed:
  seednum: 11445

