data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.4843265088646992
  epochs: 257
  momentum: 0.3605485063886856
  weight_decay: 0.0023067190135482593
  label_smoothing: 0.4434589823778469
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 153

seed:
  seednum: 921

