data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.1989542157029442
  epochs: 296
  momentum: 0.597132276352403
  weight_decay: 7.854592355869882e-05
  label_smoothing: 0.20371145473516808
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 209

seed:
  seednum: 9239

