data:
  gpu: 0
  num_workers: 8
  train_dataset: /tmp/cifar_train.beton
  val_dataset: /tmp/cifar_test.beton

training:
  batch_size: 4196
  lr: 1.4557916623227765
  epochs: 223
  momentum: 0.5684339488686485
  weight_decay: 0.00015316508243748712
  label_smoothing: 0.19172075941288885
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 217

seed:
  seednum: 2345

