data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.9545212986603865
  epochs: 156
  momentum: 0.9562797659795468
  weight_decay: 0.003331046366230721
  label_smoothing: 0.2780524202713056
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 88

seed:
  seednum: 12637

