data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 1.2898521023117924
  epochs: 148
  momentum: 0.291856160990194
  weight_decay: 0.007124833753435912
  label_smoothing: 0.22860186831933496
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 6

seed:
  seednum: 13302

