data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 3.9740219600088245
  epochs: 92
  momentum: 0.9384832122056003
  weight_decay: 0.005310799376397867
  label_smoothing: 0.2128883080815248
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 41

seed:
  seednum: 21794

