data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.134244166317467
  epochs: 300
  momentum: 0.9985050426165946
  weight_decay: 7.501289432555264e-05
  label_smoothing: 0.13519279384695942
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 293

seed:
  seednum: 19202

