data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.00397381192826164
  epochs: 292
  momentum: 0.5395826576640784
  weight_decay: 1.142069885871076e-06
  label_smoothing: 0.13562659484419098
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 269

seed:
  seednum: 234

