data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  batch_size: 4196
  lr: 0.9459029828470981
  epochs: 116
  momentum: 0.7036393255344799
  weight_decay: 0.0039503799596839
  label_smoothing: 0.32731194797050367
  lr_tta: True
  num_workers: 8
  lr_peak_epoch: 37

seed:
  seednum: 25693

