data:
  gpu: 0
  num_workers: 8
  train_dataset: /tmp/cifar_train.beton
  val_dataset: /tmp/cifar_test.beton
training:
  epochs: 300
  batch_size: 128
  lr: 0.1
  momentum: 0.9
  lr_peak_epoch: 5
  momentum: 0.9
  weight_decay: 0.0005
  label_smoothing: 0.1
  lr_tta: true
  num_workers: 8
