data:
  gpu: 0
  num_workers: 8
  train_dataset: /tmp/cifar_train.beton
  val_dataset: /tmp/cifar_test.beton

training:
  weight_decay: 0.0005
  num_workers: 8
  momentum: 0.9
  lr_tta: True
  lr_peak_epoch: 5
  lr: 0.1
  label_smoothing: 0.01
  epochs: 300
  batch_size: 128

