data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train2.beton
  val_dataset: /scratch/zd2260/cifar_test2.beton

training:
  weight_decay: 0.0005
  num_workers: 8
  momentum:  0.9
  lr_tta: False
  lr_peak_epoch: 10
  lr:  0.001
  label_smoothing:  0.1
  epochs: 1000
  batch_size: 400

seed:
  seednum: 1118

