data:
  gpu: 0
  num_workers: 8
  train_dataset: /scratch/zd2260/cifar_train.beton
  val_dataset: /scratch/zd2260/cifar_test.beton

training:
  weight_decay: 0.0005
  num_workers: 8
  momentum:  0.9
  lr_tta: False
  lr_peak_epoch: 10
  lr:  0.1
  label_smoothing:  0.3437404848076403
  epochs: 300
  batch_size: 128

seed:
  seednum: 54321

